name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm ci && npm install react preact
    - name: test
      run: npm run test
      env:
        CI: true
    - name: e2e
      run: npm run e2e
      env:
        CI: true
    - name: lint
      run: npm run lint
      env:
        CI: true
    - name: build
      run: npm run build
      env:
        CI: true
